### ISSUE TITLE
Module does not load

### ISSUE THREAD

**Issue by sker65** [nesges/Fhem-Modules#2]
POSIX::tmpnam() at ./FHEM/98_FireTV.pm line 26
FHEM 5.8 running on Raspberry Pi 3

**Comment by Eistee82** [comment]
Same Problem here:
`BEGIN failed--compilation aborted at ./FHEM/98_FireTV.pm line 26.
2018.06.09 17:26:47 0: Unimplemented: POSIX::tmpnam() at ./FHEM/98_FireTV.pm line 26.

BEGIN failed--compilation aborted at ./FHEM/98_FireTV.pm line 26.
 Unimplemented: POSIX::tmpnam() at ./FHEM/98_FireTV.pm line 26.
2018.06.09 17:26:47 1: reload: Error:Modul 98_FireTV deactivated:
2018.06.09 17:26:47 1: PERL WARNING: Unimplemented: POSIX::tmpnam(): use File::Temp instead at /usr/local/lib/perl5/5.26.1/armv7l-linux/POSIX.pm line 185.`

**Comment by nesges** [comment]
the current version replaces POSIX::tmpnam with File::Temp. please update and try this version
